services:
  jyotish_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: jyotish_api
    ports:
      - "80:9393"
    volumes:
      - ./api:/var/www/api
      - /var/www/api/vendor               